[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  framework = "#custom"
  command = "npm start"
  port = 3000

[context.production.environment]
  NODE_VERSION = "18.20.2"
  NODE_OPTIONS = "--openssl-legacy-provider"
