[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18.17.0" }

[build.environment]
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist" 